### ISSUE TITLE
Fix picture downloads

### ISSUE THREAD

**Issue by arielkoiman** [opencleveland/large-lots#20]

**Comment by cwang912** [comment]
I messed around with some of the things that you commented out to change databases, but that obviously didn't work, since the database was already saved and sqlite wouldn't interpret it.

The reference URL listed in the django admin interface seems to refer to the file structure on the instance -- I know Ariel was saving the images locally, and that's what it's doing, but the URL link in django doesn't account for this right now. Either we need to find a way to reference local images through django to an external URL, or something else.

Right now the files are dispersed in various plan folders -- I don't know if that's going to be a problem in production or not.

**Comment by cwang912** [comment]
If we want to serve static files I think we'll have to configure the MEDIA_ROOT and MEDIA_URL variables. Datamade didn't do it this way, so we don't have that to build off of.

**Comment by pkoepke** [comment]
What exactly is the bug? Is it: we can upload images and save them locally on the server, but when we try to retrieve them they're not found?

So where is Django saving the files to currently, and where is it getting that filepath from?

When it tries to retrieve files, where is it looking?

**Comment by cwang912** [comment]
Yes. I'm not sure how Django looks for the files currently, but they are saved to a folder called "plans".

https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/ has some notes, but I'm assuming we aren't worried about the scale and that saving files locally isn't an issue.

**Comment by pkoepke** [comment]
Yeah, I set up an S3 instance but honestly I think that's overkill at this point. If we start running low on space I can give us more local storage or then we can migrate to S3.

How can I access the page/link that has the error while retrieving the files? That might help narrow down what's going on.

**Comment by cwang912** [comment]
If you log into the admin part of the site and click on people's applications, there should be a link to their uploaded image. I'm trying to go to:

.../django-admin/lots_admin/application/15/plans/Bubba-Bubbakins-1431391415_ncdc.jpg

But it throws an error.

**Comment by cwang912** [comment]
404: application object with primary key u'15/plans/Bubba-Bubbakins-1431391415_ncdc.jpg' does not exist.

**Comment by arielkoiman** [comment]
@cwang912, you ended up being on the nose about MEDIA_URL. That's what it was--I'll note that in the local settings template file.
