### ISSUE TITLE
Automate data load process

### ISSUE THREAD

**Issue by pkoepke** [opencleveland/large-lots#34]
NST is updated weekly; we should write a script that updates the data in our DB weekly based on NST.

**Comment by arielkoiman** [comment]
It looks like CartoDB has a handy API; @eamonjohnson, do we have something API-like for NST? Sorry if that's a redundant question; I haven't been focused on the data loading process so far.

**Comment by eamonjohnson** [comment]
NST has an API, but it's not documented.  Carter and I talked through it and decided to go with manual updates for now.

**Comment by skorasaurus** [comment]
Since getting updated data directly from the landbank was a pain (due to their lack of response and technical limitations) and carto's ability to synchronize data sets published through ARCGIS (which NEOCANDO publishes); we'll be able to automate the data loading process. 

This synchronization does require an enterprise subscription to carto but we have one courtesy of Carto and code for america. This will require some minor rewrites of the sql queries since the column names are different - (I am looking into this at the moment).

**Comment by aprilhirsh** [comment]
Sorry I hadn't been communicating through Github. The feature service should be accessible here:
https://services3.arcgis.com/8a4lrasHsYiB0dvX/arcgis/rest/services/Side_Yard_Candidate/FeatureServer

I will update the service monthly to start. The service represents City of Cleveland land-bank owned vacant lots, as designated by the land use code. The lots are then subsetted and lots in City of Cleveland target development areas are excluded, as they are not likely to be approved for a side-yard.

**Comment by skorasaurus** [comment]
tracked in https://github.com/opencleveland/large-lots/pull/44

**Comment by skorasaurus** [comment]
done!
